theme: jekyll-theme-minimal
show_downloads: false
title: Arbor Oaks Home Owners Association Bethany Oregon
description: A single family home community in the beautiful Bethany area
whitelist:
  - jekyll-redirect-from
plugins:
  - jekyll-redirect-from
