theme: jekyll-theme-minimal
show_downloads: false
title: Arbor Oaks HOA
logo: arbor-oaks.png
description: A community of single family and town homes in the beautiful Bethany area
whitelist:
  - jekyll-redirect-from
plugins:
  - jekyll-redirect-from
